---
name: CI

on:
  push:
  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  commitQueue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Install dependencies
      - name: Install jq
        run: sudo apt-get install jq -y
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Get Pull Requests
      - name: Get Pull Requests
        uses: octokit/graphql-action@v2.x
        id: get_mergable_pull_requests
        with:
          query: |
            query release($owner:String!,$repo:String!, $base_ref:String!) {
              repository(owner:$owner, name:$repo) {
                pullRequests(baseRefName: $base_ref, labels: ["commit-queue"], states: OPEN, last: 100) {
                  nodes {
                    number
                  }
                }
              }
            }
          owner: "mmarchini-oss"
          repo: "automated-merge-test"
          base_ref: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: replace this block with ncu
      - name: Do the thing
        run: ./land-stuff.sh mmarchini-oss automated-merge-test commit-queue commit-queue-failed gh ${{ secrets.GITHUB_TOKEN }} $(echo '${{ steps.get_mergable_pull_requests.outputs.data }}' | jq '.repository.pullRequests.nodes | map(.number) | .[]')
