---
name: CI

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  commitQueue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const [ org, repo ] = github.repository.split("/")
            console.log(`:set-env: GITHUB_ORG=${org}`)
            console.log(`:set-env: GITHUB_REPO=${repo}`)
            return { org, repo }
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(github) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job context
        run: echo "$GITHUB_ORG $GITHUB_REPO"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(step) }}
        run: echo "$JOB_CONTEXT"
      # - name: Dump job context
      #   env:
      #     JOB_CONTEXT: ${{ toJson(result) }}
      #   run: echo "$JOB_CONTEXT"
      - uses: octokit/graphql-action@v2.x
        id: get_mergable_pull_requests
        with:
          query: |
            query release($owner:String!,$repo:String!, $baseRefName:String!) {
              repository(owner:$owner, name:$repo) {
                pullRequests(baseRefName: $baseRefName, labels: ["commit-queue"], states: OPEN, last: 100) {
                  nodes {
                    number
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
          baseRefName: "master"
          # baseRefName: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_mergable_pull_requests.outputs.data }}'"
