---
name: CI

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  commitQueue:
    runs-on: ubuntu-latest
    steps:
      - id: get_context
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // console.log(context)
            // console.log(github)
            console.log(1)
            const { payload } = context;
            console.log(1)
            const { repository } = payload;
            const repo = repository.name;
            console.log(2)
            const owner = repository.owner.name;
            console.log(3)
            console.log(`::set-env GITHUB_OWNER=${owner}`)
            console.log(4)
            console.log(`::set-env GITHUB_REPO=${repo}`)
            console.log(5)
            return { owner, repo }
      - name: Dump job github
        env:
          JOB_CONTEXT: ${{ toJson(github) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job env
        run: echo "$GITHUB_OWNER $GITHUB_REPO"
      - name: Dump job job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job toJson steps
        env:
          JOB_CONTEXT: ${{ toJson(steps.get_context.outputs) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job toJson steps
        env:
          JOB_CONTEXT: ${{ toJson(toJson(steps.get_context.outputs).result).owner }}
        run: echo "$JOB_CONTEXT"
      - name: Dump job outputs steps
        env:
          JOB_CONTEXT: ${{ steps.get_context.outputs.result.owner }}
        run: echo "$JOB_CONTEXT"
      # - name: Dump job steps
      #   env:
      #     JOB_CONTEXT: ${{ steps.get_context.outputs }}
      #   run: echo "$JOB_CONTEXT"
      # - name: Dump job context
      #   env:
      #     JOB_CONTEXT: ${{ toJson(result) }}
      #   run: echo "$JOB_CONTEXT"
      - uses: octokit/graphql-action@v2.x
        id: get_mergable_pull_requests
        with:
          query: |
            query release($owner:String!,$repo:String!, $baseRefName:String!) {
              repository(owner:$owner, name:$repo) {
                pullRequests(baseRefName: $baseRefName, labels: ["commit-queue"], states: OPEN, last: 100) {
                  nodes {
                    number
                  }
                }
              }
            }
          # owner: ${{ steps.result.owner }}
          owner: ${{ toJson(steps.get_context.outputs.result).owner }}
          repo: ${{ steps.get_context.outputs.result.repo }}
          baseRefName: "master"
          # baseRefName: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_mergable_pull_requests.outputs.data }}'"
