---
name: CI

on:
  push:
  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  commitQueue:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_mergable_pull_requests
        with:
          query: |
            query release($owner:String!,$repo:String!, $base_ref:String!) {
              repository(owner:$owner, name:$repo) {
                pullRequests(baseRefName: $base_ref, labels: ["commit-queue"], states: OPEN, last: 100) {
                  nodes {
                    number
                  }
                }
              }
            }
          owner: "mmarchini-oss"
          repo: "automated-merge-test"
          base_ref: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_mergable_pull_requests.outputs.data }}'"
