---
name: Jenkins

on:
  repository_dispatch:
    types: ["jenkins.node-test-pull-request.pending"]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: echo "I'm alive!"

