name: test-linux

on:
  pull_request:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: 3.8
  FLAKY_TESTS: dontcare

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Set up Node.js ${{ env.PYTHON_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: v14
      - name: Test
        run: |
          mkdir -p out/Release
          cp $(which node) out/Release/node
          echo "::add-matcher::.github/workflows/js-tests-problem-matcher.json"
          make run-ci -j2 V=1 TEST_CI_ARGS="-p dots" CI_JS_SUITES="parallel"
